let events=[];let statusFilter='all',lastFocused=null;
const $=id=>document.getElementById(id),D={container:$('eventsContainer'),empty:$('emptyState'),emptyTitle:$('emptyTitle'),emptyDesc:$('emptyDescription'),loading:$('loadingSpinner'),search:$('searchInput'),clear:$('clearSearch'),category:$('categoryFilter'),status:[...document.querySelectorAll('.status-filter')],open:$('openAddEventModal'),modal:$('addEventModal'),close:$('closeModal'),cancel:$('cancelModal'),form:$('addEventForm'),submit:$('submitEvent'),title:$('eventTitle'),venue:$('eventVenue'),sd:$('eventStartDate'),st:$('eventStartTime'),ed:$('eventEndDate'),et:$('eventEndTime'),cat:$('eventCategory'),desc:$('eventDescription'),featured:$('eventFeatured'),guest:$('featuredPersonName'),role:$('featuredPersonRole'),guestBox:$('featuredGuestFields'),password:$('adminPassword'),count:$('charCount'),toast:$('toast'),toastMsg:$('toastMessage')};
const clean=v=>typeof v==='string'?v.trim().replace(/\0/g,''):'';
const analytics=(action,details={})=>console.log('[Analytics] User interacted with Independent Bookstore Events Page',{action,timestamp:new Date().toISOString(),...details});
function toast(m,type='info'){D.toastMsg.textContent=m;D.toast.className=`toast ${type}`;D.toast.hidden=false;clearTimeout(D.toast._t);D.toast._t=setTimeout(()=>D.toast.hidden=true,3500)}
function busy(b,on,text){if(on){b.dataset.original=b.textContent;b.textContent=text;b.disabled=true;b.setAttribute('aria-busy','true')}else{b.textContent=b.dataset.original||b.textContent;delete b.dataset.original;b.disabled=false;b.removeAttribute('aria-busy')}}
async function api(url,opt={}){const r=await fetch(url,{...opt,signal:opt.signal||AbortSignal.timeout(10000)});let d={};try{d=await r.json()}catch(_){}if(!r.ok)throw new Error(d.error||'Request failed');return d}
async function load(){for(let i=0;i<2;i++){try{return(await api('/api/events',{headers:{Accept:'application/json'}})).events||[]}catch(e){if(i)throw e;await new Promise(r=>setTimeout(r,800))}}}
function status(e,now=new Date()){const s=new Date(e.starts_at),x=new Date(e.ends_at);if(Number.isNaN(s)||Number.isNaN(x))return'past';if(now<s)return'upcoming';if(now<x)return'current';return'past'}
function dateText(e){const s=new Date(e.starts_at),x=new Date(e.ends_at);if(Number.isNaN(s)||Number.isNaN(x))return'Invalid date/time';const sd=new Intl.DateTimeFormat(undefined,{dateStyle:'medium'}).format(s),st=new Intl.DateTimeFormat(undefined,{timeStyle:'short'}).format(s),et=new Intl.DateTimeFormat(undefined,{timeStyle:'short'}).format(x);return s.toDateString()===x.toDateString()?`${sd} · ${st}–${et}`:`${new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short'}).format(s)} – ${new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short'}).format(x)}`}
const catName=v=>({'book-club':'Book Club','author-event':'Author Event',workshop:'Workshop',reading:'Reading',signing:'Book Signing'})[v]||v;
function list(){const q=clean(D.search.value).toLowerCase(),cat=D.category.value;return events.filter(e=>{const s=status(e),text=`${e.title} ${e.venue} ${e.description} ${e.featured_person_name||''}`.toLowerCase();return(!q||text.includes(q))&&(cat==='all'||e.category===cat)&&(statusFilter==='all'||s===statusFilter)}).sort((a,b)=>new Date(a.starts_at)-new Date(b.starts_at))}
function card(e){const s=status(e),c=document.createElement('article');c.className=`event-card status-${s}${e.is_featured?' featured-event':''}`;c.setAttribute('role','listitem');
 const h=document.createElement('div');h.className='event-card-header';const t=document.createElement('h3');t.className='event-title';t.textContent=e.title;const b=document.createElement('span');b.className='event-status-badge';b.textContent=s==='current'?'Current':s==='upcoming'?'Upcoming':'Past';h.append(t,b);c.append(h);
 if(e.is_featured){const f=document.createElement('div');f.className='featured-badge';f.textContent='★ Featured Event';c.append(f)}
 const cat=document.createElement('span');cat.className='event-category-badge';cat.textContent=catName(e.category);const v=document.createElement('div');v.className='event-venue';v.textContent=`Venue: ${e.venue}`;const dt=document.createElement('div');dt.className='event-datetime';dt.textContent=`Date & time: ${dateText(e)}`;const d=document.createElement('p');d.className='event-description';d.textContent=e.description;c.append(cat,v,dt,d);
 if(e.is_featured){const g=document.createElement('div');g.className='featured-guest';const r=document.createElement('strong');r.textContent=`★ ${e.featured_person_role}: `;const n=document.createElement('span');n.textContent=e.featured_person_name;g.append(r,n);c.append(g)}
 const pc=document.createElement('p');pc.className='event-participants';pc.textContent=`${Number(e.participants)||0} participant${Number(e.participants)===1?'':'s'}`;c.append(pc);const actions=document.createElement('div');actions.className='event-card-actions';const p=document.createElement('button');p.type='button';p.className='participate-btn';p.textContent=s==='past'?'Event Completed':'Participate';p.disabled=s==='past';p.setAttribute('aria-label',p.disabled?`${e.title} is completed`:`Participate in ${e.title}`);const del=document.createElement('button');del.type='button';del.className='delete-btn';del.textContent='Delete';del.setAttribute('aria-label',`Delete event: ${e.title}`);
 p.addEventListener('click',async()=>{busy(p,true,'Saving...');try{const r=await api('/api/events',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'participate',eventId:e.id})});if(r.alreadyParticipated){toast('Your participation has already been recorded.','info');return}events=await load();render();toast('Your participation has been recorded successfully!','success');analytics('PARTICIPATE',{eventId:e.id})}catch(err){toast(err.message.includes('already')?'Your participation has already been recorded.':'Unable to record your participation. Please check your connection and try again.','error')}finally{busy(p,false)}});
 del.addEventListener('click',async()=>{if(!confirm(`Delete “${e.title}”? This cannot be undone.`))return;const pw=prompt('Enter admin password:');if(!pw)return;busy(del,true,'Deleting...');try{await api(`/api/events?id=${encodeURIComponent(e.id)}`,{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:pw})});events=await load();render();toast('Event deleted successfully.','success');analytics('DELETE_EVENT',{eventId:e.id})}catch(err){toast(err.message||'Unable to delete event. Please try again.','error')}finally{busy(del,false)}});actions.append(p,del);c.append(actions);return c}
function section(title,s,items){const sec=document.createElement('section');sec.className='event-status-section';const h=document.createElement('div');h.className='event-section-heading';const t=document.createElement('h2');t.textContent=title;const n=document.createElement('span');n.className='event-section-count';n.textContent=items.length;h.append(t,n);const grid=document.createElement('div');grid.className='events-grid';grid.setAttribute('role','list');items.forEach(e=>grid.append(card(e)));sec.append(h,grid);return sec}
function render(){D.container.replaceChildren();const a=list();if(!a.length){D.empty.hidden=false;D.emptyTitle.textContent='No events found';D.emptyDesc.textContent='Try a different search term, category, or status filter.';return}D.empty.hidden=true;const f=document.createDocumentFragment();[['Current Events','current'],['Upcoming Events','upcoming'],['Past Events','past']].forEach(([t,s])=>{const x=a.filter(e=>status(e)===s);if(x.length)f.append(section(t,s,x))});D.container.append(f);analytics('RENDER_EVENTS',{count:a.length,filter:statusFilter})}
function setStatus(s){statusFilter=s;D.status.forEach(b=>{const on=b.dataset.status===s;b.classList.toggle('active',on);b.setAttribute('aria-pressed',String(on))});render()}
function clearErrors(){document.querySelectorAll('.form-error').forEach(x=>x.textContent='');document.querySelectorAll('.form-input').forEach(x=>{x.classList.remove('error');x.removeAttribute('aria-invalid')})}
function formErrors(x){const e={};if(clean(x.title).length<2)e.title='Title must be at least 2 characters.';if(clean(x.venue).length<2)e.venue='Venue must be at least 2 characters.';if(!x.sd)e.sd='Start date is required.';if(!x.st)e.st='Start time is required.';if(!x.ed)e.ed='End date is required.';if(!x.et)e.et='End time is required.';if(x.sd&&x.st&&x.ed&&x.et&&new Date(`${x.ed}T${x.et}`)<=new Date(`${x.sd}T${x.st}`))e.ed='End date and time must be after the start date and time.';if(!['book-club','author-event','workshop','reading','signing'].includes(x.cat))e.cat='Please select a valid category.';if(clean(x.desc).length<5)e.desc='Description must be at least 5 characters.';if(x.featured&&clean(x.guest).length<2)e.guest='Featured person name is required.';if(x.featured&&clean(x.role).length<2)e.role='Featured person role is required.';if(!clean(x.password))e.password='Admin password is required.';return e}
function showErrors(es){Object.entries(es).forEach(([k,m])=>{const map={title:'eventTitle',venue:'eventVenue',sd:'eventStartDate',st:'eventStartTime',ed:'eventEndDate',et:'eventEndTime',cat:'eventCategory',desc:'eventDescription',guest:'featuredPersonName',role:'featuredPersonRole',password:'adminPassword'},input=$(map[k]),err=$(k+'Error');if(input){input.classList.add('error');input.setAttribute('aria-invalid','true')}if(err)err.textContent=m})}
function toggleGuest(){const on=D.featured.checked;D.guestBox.hidden=!on;D.guest.required=on;D.role.required=on}
function openModal(){lastFocused=document.activeElement;D.form.reset();clearErrors();D.guestBox.hidden=true;D.modal.classList.add('open');D.modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';const d=new Date().toISOString().slice(0,10);D.sd.value=d;D.ed.value=d;D.sd.min=d;D.ed.min=d;D.title.focus();analytics('OPEN_MODAL')}
function closeModal(){D.modal.classList.remove('open');D.modal.setAttribute('aria-hidden','true');document.body.style.overflow='';lastFocused?.focus?.()}
async function submit(e){e.preventDefault();const x={title:D.title.value,venue:D.venue.value,sd:D.sd.value,st:D.st.value,ed:D.ed.value,et:D.et.value,cat:D.cat.value,desc:D.desc.value,featured:D.featured.checked,guest:D.guest.value,role:D.role.value,password:D.password.value};clearErrors();const es=formErrors(x);if(Object.keys(es).length){showErrors(es);toast('Please correct the highlighted fields.','error');return}busy(D.submit,true,'Saving...');try{await api('/api/events',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:clean(x.title),venue:clean(x.venue),starts_at:new Date(`${x.sd}T${x.st}`).toISOString(),ends_at:new Date(`${x.ed}T${x.et}`).toISOString(),category:x.cat,description:clean(x.desc),is_featured:x.featured,featured_person_name:clean(x.guest),featured_person_role:clean(x.role),password:x.password})});events=await load();closeModal();render();toast('Event added successfully!','success');analytics('ADD_EVENT')}catch(err){toast(err.message||'Unable to save event. Please try again.','error')}finally{busy(D.submit,false)}}
async function init(){D.loading.hidden=false;try{events=await load();render()}catch(e){D.empty.hidden=false;D.emptyTitle.textContent='Unable to load events';D.emptyDesc.textContent='Please check your internet connection and try again.';toast('Unable to connect to the event database.','error')}finally{D.loading.hidden=true}}
D.status.forEach(b=>b.addEventListener('click',()=>setStatus(b.dataset.status)));D.search.addEventListener('input',()=>{D.clear.classList.toggle('visible',!!D.search.value);render()});D.clear.addEventListener('click',()=>{D.search.value='';D.clear.classList.remove('visible');render();D.search.focus()});D.category.addEventListener('change',render);D.open.addEventListener('click',openModal);D.close.addEventListener('click',closeModal);D.cancel.addEventListener('click',closeModal);D.modal.addEventListener('click',e=>{if(e.target===D.modal)closeModal()});D.form.addEventListener('submit',submit);D.featured.addEventListener('change',toggleGuest);D.desc.addEventListener('input',()=>D.count.textContent=D.desc.value.length);document.addEventListener('keydown',e=>{if(e.key==='Escape'&&D.modal.classList.contains('open'))closeModal()});setInterval(()=>{if(events.length)render()},60000);document.addEventListener('DOMContentLoaded',init);
